name: CD

on:
  push:
    branches: master

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name:  Install JupyterBook
      run: pip install jupyter-book
      shell: bash -l {0}

    - name: Make book
      run: jupyter-book create site --content-folder docs
      shell: bash -l {0}

    - name: Build book
      run: jupyter-book build site
      shell: bash -l {0}

    - name: Deploy
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      users: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: site
        force_orphan: true
        enable_jekyll: true
        cname: github.com
